  <div id="footer">
  <?php
	// $pglist = array("people", "skyaura", "spacetourism", "imagination", "flight", "unique", "puzzles", "life", "tutorial/index", "contact", "professional");
	// shuffle($pglist);
  ?>
  	<p>
	<?php
	  // echo "<a class=\"bright\" onMouseOver=\"window.status='Take my chance!'; return true\" href='http://www.mendedreality.com/".$pglist[1].".php'>Be like Shen Ge and go random!</a><br /><br />";
	?>
   <hr/>
   http://www.shenge.us<br/>
   Copyright 2013 </p>
   
   </div>
 
 </div>
</body>
</html>
